#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CrossbowBolt

#include "Basic.hpp"

#include "CrossbowBolt_classes.hpp"
#include "CrossbowBolt_parameters.hpp"


namespace SDK
{

// Function crossbowBolt.crossbowBolt_C.ExecuteUbergraph_crossbowBolt
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACrossbowBolt_C::ExecuteUbergraph_crossbowBolt(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("crossbowBolt_C", "ExecuteUbergraph_crossbowBolt");

	Params::CrossbowBolt_C_ExecuteUbergraph_crossbowBolt Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function crossbowBolt.crossbowBolt_C.Dest
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           DestroyedActor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACrossbowBolt_C::Dest(class AActor* DestroyedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("crossbowBolt_C", "Dest");

	Params::CrossbowBolt_C_Dest Parms{};

	Parms.DestroyedActor = DestroyedActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function crossbowBolt.crossbowBolt_C.resetLoc
// (BlueprintCallable, BlueprintEvent)

void ACrossbowBolt_C::ResetLoc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("crossbowBolt_C", "resetLoc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function crossbowBolt.crossbowBolt_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ACrossbowBolt_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("crossbowBolt_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function crossbowBolt.crossbowBolt_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACrossbowBolt_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("crossbowBolt_C", "ReceiveTick");

	Params::CrossbowBolt_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

