#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Custom_menu

#include "Basic.hpp"

#include "Custom_menu_classes.hpp"
#include "Custom_menu_parameters.hpp"


namespace SDK
{

// Function custom_menu.custom_menu_C.BndEvt__menuadditions_ModSettingsButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UCustom_menu_C::BndEvt__menuadditions_ModSettingsButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("custom_menu_C", "BndEvt__menuadditions_ModSettingsButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function custom_menu.custom_menu_C.BndEvt__menuadditions_ModListButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UCustom_menu_C::BndEvt__menuadditions_ModListButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("custom_menu_C", "BndEvt__menuadditions_ModListButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function custom_menu.custom_menu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCustom_menu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("custom_menu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function custom_menu.custom_menu_C.BndEvt__custom_menu_DonateButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UCustom_menu_C::BndEvt__custom_menu_DonateButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("custom_menu_C", "BndEvt__custom_menu_DonateButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function custom_menu.custom_menu_C.BndEvt__custom_menu_SocialsButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UCustom_menu_C::BndEvt__custom_menu_SocialsButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("custom_menu_C", "BndEvt__custom_menu_SocialsButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function custom_menu.custom_menu_C.ExecuteUbergraph_custom_menu
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCustom_menu_C::ExecuteUbergraph_custom_menu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("custom_menu_C", "ExecuteUbergraph_custom_menu");

	Params::Custom_menu_C_ExecuteUbergraph_custom_menu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

