#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Flammable

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function flammable.flammable_C.ExecuteUbergraph_flammable
// 0x0580 (0x0580 - 0x0000)
struct Flammable_C_ExecuteUbergraph_flammable final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_fuel;                           // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0xC];                                       // 0x0014(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FParticleSysParam                      K2Node_MakeStruct_ParticleSysParam;                // 0x0020(0x0080)(IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_bound_Origin;                             // 0x00A4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_bound_BoxExtent;                          // 0x00B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue;      // 0x00BC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Subtract_VectorFloat_ReturnValue;         // 0x00C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D5[0x3];                                       // 0x00D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetMaxElement_ReturnValue;                // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x00DC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EC[0x4];                                       // 0x00EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FParticleSysParam                      K2Node_MakeStruct_ParticleSysParam_1;              // 0x00F0(0x0080)(IsPlainOldData, NoDestructor)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0170(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x0174(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue;           // 0x0178(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult; // 0x0180(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	TScriptInterface<class IInt_objects_C>        K2Node_DynamicCast_AsInt_Objects;                  // 0x0208(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0218(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_219[0x3];                                      // 0x0219(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x021C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0220(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0230(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetWorldDeltaSeconds_ReturnValue;         // 0x0238(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FMax_ReturnValue;                         // 0x023C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_CustomEvent_DestroyedActor;                 // 0x0240(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0248(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0249(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_24A[0x2];                                      // 0x024A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x024C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_251[0x3];                                      // 0x0251(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0254(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0258(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBoxSphereBounds                       CallFunc_GetBounds_ReturnValue;                    // 0x025C(0x001C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_278[0x8];                                      // 0x0278(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x0280(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_TransformLocation_ReturnValue;            // 0x02B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x02BC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorFloat_ReturnValue;              // 0x02C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetComponentRotation_ReturnValue_1;    // 0x02D4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TDelegate<void(class AActor* DestroyedActor)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x02E0(0x0010)(ZeroConstructor, NoDestructor)
	float                                         CallFunc_RandomFloatInRange_ReturnValue_1;         // 0x02F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x02F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x02F8(0x0010)(ConstParm, ReferenceParm)
	TArray<struct FHitResult>                     CallFunc_BoxTraceMulti_OutHits;                    // 0x0308(0x0010)(ReferenceParm, ContainsInstancedReference)
	bool                                          CallFunc_BoxTraceMulti_ReturnValue;                // 0x0318(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_319[0x3];                                      // 0x0319(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_Array_Get_Item;                           // 0x031C(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_isUnderwater_ReturnValue;                 // 0x03A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x03A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x03A6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3A7[0x1];                                      // 0x03A7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x03A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x03AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x03B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x03BC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x03C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x03D4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x03E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x03E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x03F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x03F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0400(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x0404(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0408(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x040C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0418(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_424[0x4];                                      // 0x0424(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     CallFunc_GetMaterial_ReturnValue;                  // 0x0428(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IInt_objects_C>        K2Node_DynamicCast_AsInt_Objects_1;                // 0x0430(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0440(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0441(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_442[0x6];                                      // 0x0442(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_GetPhysicalMaterial_ReturnValue;          // 0x0448(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IInt_objects_C>        K2Node_DynamicCast_AsInt_Objects_2;                // 0x0450(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0460(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0461(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_isFlammable_isFlammable;                  // 0x0462(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0463(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_isFlammable_isFlammable_1;                // 0x0464(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_465[0x3];                                      // 0x0465(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0468(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x046C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsBeingDestroyed_ReturnValue;             // 0x046D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsBeingDestroyed_ReturnValue_1;           // 0x046E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x046F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0470(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0471(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0472(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_isUnderwater_ReturnValue_1;               // 0x0473(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x0474(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_475[0x3];                                      // 0x0475(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_1;        // 0x0478(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VictoryFloatMinusEquals_FloatOut;         // 0x047C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x0480(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_481[0x3];                                      // 0x0481(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0484(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_InvalidateTimerHandle_ReturnValue;     // 0x0488(0x0008)(NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        CallFunc_K2_GetRootComponent_ReturnValue;          // 0x0490(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x0498(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_499[0x7];                                      // 0x0499(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_DynamicCast_AsPrimitive_Component;          // 0x04A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x04A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A9[0x7];                                      // 0x04A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   K2Node_DynamicCast_AsStatic_Mesh_Component;        // 0x04B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x04B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4B9[0x3];                                      // 0x04B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Conv_FloatToVector_ReturnValue;           // 0x04BC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_2;        // 0x04C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4CC[0x4];                                      // 0x04CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FParticleSysParam                      K2Node_MakeStruct_ParticleSysParam_2;              // 0x04D0(0x0080)(IsPlainOldData, NoDestructor)
	int32                                         CallFunc_Array_Add_ReturnValue_2;                  // 0x0550(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_554[0x4];                                      // 0x0554(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0558(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_RandomBoolWithWeight_ReturnValue;         // 0x0560(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0561(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_RandomBoolWithWeight_ReturnValue_1;       // 0x0562(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0563(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_564[0x4];                                      // 0x0564(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AMainGamemode_C*                        CallFunc_getMainGamemode_AsMain_Gamemode;          // 0x0568(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMainGamemode_C*                        CallFunc_getMainGamemode_AsMain_Gamemode_1;        // 0x0570(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_RemoveItem_ReturnValue;             // 0x0578(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_579[0x3];                                      // 0x0579(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x057C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Flammable_C_ExecuteUbergraph_flammable) == 0x000010, "Wrong alignment on Flammable_C_ExecuteUbergraph_flammable");
static_assert(sizeof(Flammable_C_ExecuteUbergraph_flammable) == 0x000580, "Wrong size on Flammable_C_ExecuteUbergraph_flammable");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, EntryPoint) == 0x000000, "Member 'Flammable_C_ExecuteUbergraph_flammable::EntryPoint' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_GetOwner_ReturnValue) == 0x000008, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_CustomEvent_fuel) == 0x000010, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_CustomEvent_fuel' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_MakeStruct_ParticleSysParam) == 0x000020, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_MakeStruct_ParticleSysParam' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Array_Add_ReturnValue) == 0x0000A0, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_bound_Origin) == 0x0000A4, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_bound_Origin' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_bound_BoxExtent) == 0x0000B0, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_bound_BoxExtent' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_K2_GetComponentRotation_ReturnValue) == 0x0000BC, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_K2_GetComponentRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Subtract_VectorFloat_ReturnValue) == 0x0000C8, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Subtract_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_K2_AttachToComponent_ReturnValue) == 0x0000D4, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_GetMaxElement_ReturnValue) == 0x0000D8, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_GetMaxElement_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x0000DC, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Divide_FloatFloat_ReturnValue) == 0x0000E8, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_MakeStruct_ParticleSysParam_1) == 0x0000F0, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_MakeStruct_ParticleSysParam_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Add_FloatFloat_ReturnValue) == 0x000170, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Array_Add_ReturnValue_1) == 0x000174, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_SpawnSoundAttached_ReturnValue) == 0x000178, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_SpawnSoundAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult) == 0x000180, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_K2_SetWorldLocationAndRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_DynamicCast_AsInt_Objects) == 0x000208, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_DynamicCast_AsInt_Objects' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_DynamicCast_bSuccess) == 0x000218, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_RandomFloatInRange_ReturnValue) == 0x00021C, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_CreateDelegate_OutputDelegate) == 0x000220, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000230, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_GetWorldDeltaSeconds_ReturnValue) == 0x000238, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_GetWorldDeltaSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_FMax_ReturnValue) == 0x00023C, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_FMax_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_CustomEvent_DestroyedActor) == 0x000240, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_CustomEvent_DestroyedActor' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsValid_ReturnValue) == 0x000248, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsValid_ReturnValue_1) == 0x000249, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, Temp_int_Loop_Counter_Variable) == 0x00024C, "Member 'Flammable_C_ExecuteUbergraph_flammable::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsValid_ReturnValue_2) == 0x000250, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Add_IntInt_ReturnValue) == 0x000254, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, Temp_int_Array_Index_Variable) == 0x000258, "Member 'Flammable_C_ExecuteUbergraph_flammable::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_GetBounds_ReturnValue) == 0x00025C, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_GetBounds_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x000280, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_TransformLocation_ReturnValue) == 0x0002B0, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_TransformLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Add_VectorVector_ReturnValue) == 0x0002BC, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Add_VectorFloat_ReturnValue) == 0x0002C8, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Add_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_K2_GetComponentRotation_ReturnValue_1) == 0x0002D4, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_K2_GetComponentRotation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_CreateDelegate_OutputDelegate_1) == 0x0002E0, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_RandomFloatInRange_ReturnValue_1) == 0x0002F0, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_RandomFloatInRange_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x0002F4, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_MakeArray_Array) == 0x0002F8, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BoxTraceMulti_OutHits) == 0x000308, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BoxTraceMulti_OutHits' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BoxTraceMulti_ReturnValue) == 0x000318, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BoxTraceMulti_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Array_Get_Item) == 0x00031C, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_isUnderwater_ReturnValue) == 0x0003A4, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_isUnderwater_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_bBlockingHit) == 0x0003A5, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_bInitialOverlap) == 0x0003A6, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_Time) == 0x0003A8, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_Distance) == 0x0003AC, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_Location) == 0x0003B0, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_ImpactPoint) == 0x0003BC, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_Normal) == 0x0003C8, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_ImpactNormal) == 0x0003D4, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_PhysMat) == 0x0003E0, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_HitActor) == 0x0003E8, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_HitComponent) == 0x0003F0, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_HitBoneName) == 0x0003F8, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_HitItem) == 0x000400, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_ElementIndex) == 0x000404, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_FaceIndex) == 0x000408, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_TraceStart) == 0x00040C, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BreakHitResult_TraceEnd) == 0x000418, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_GetMaterial_ReturnValue) == 0x000428, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_GetMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_DynamicCast_AsInt_Objects_1) == 0x000430, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_DynamicCast_AsInt_Objects_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_DynamicCast_bSuccess_1) == 0x000440, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsValid_ReturnValue_3) == 0x000441, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_GetPhysicalMaterial_ReturnValue) == 0x000448, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_GetPhysicalMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_DynamicCast_AsInt_Objects_2) == 0x000450, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_DynamicCast_AsInt_Objects_2' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_DynamicCast_bSuccess_2) == 0x000460, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsValid_ReturnValue_4) == 0x000461, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_isFlammable_isFlammable) == 0x000462, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_isFlammable_isFlammable' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsValid_ReturnValue_5) == 0x000463, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_isFlammable_isFlammable_1) == 0x000464, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_isFlammable_isFlammable_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Array_Length_ReturnValue) == 0x000468, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Less_IntInt_ReturnValue) == 0x00046C, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsBeingDestroyed_ReturnValue) == 0x00046D, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsBeingDestroyed_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsBeingDestroyed_ReturnValue_1) == 0x00046E, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsBeingDestroyed_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsValid_ReturnValue_6) == 0x00046F, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BooleanOR_ReturnValue) == 0x000470, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsValid_ReturnValue_7) == 0x000471, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BooleanAND_ReturnValue) == 0x000472, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_isUnderwater_ReturnValue_1) == 0x000473, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_isUnderwater_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsValid_ReturnValue_8) == 0x000474, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Multiply_FloatFloat_ReturnValue_1) == 0x000478, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Multiply_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_VictoryFloatMinusEquals_FloatOut) == 0x00047C, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_VictoryFloatMinusEquals_FloatOut' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x000480, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_Event_DeltaSeconds) == 0x000484, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_K2_InvalidateTimerHandle_ReturnValue) == 0x000488, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_K2_InvalidateTimerHandle_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_K2_GetRootComponent_ReturnValue) == 0x000490, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_K2_GetRootComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_IsValid_ReturnValue_9) == 0x000498, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_IsValid_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_DynamicCast_AsPrimitive_Component) == 0x0004A0, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_DynamicCast_AsPrimitive_Component' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_DynamicCast_bSuccess_3) == 0x0004A8, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_DynamicCast_AsStatic_Mesh_Component) == 0x0004B0, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_DynamicCast_AsStatic_Mesh_Component' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_DynamicCast_bSuccess_4) == 0x0004B8, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Conv_FloatToVector_ReturnValue) == 0x0004BC, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Conv_FloatToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Multiply_FloatFloat_ReturnValue_2) == 0x0004C8, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Multiply_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, K2Node_MakeStruct_ParticleSysParam_2) == 0x0004D0, "Member 'Flammable_C_ExecuteUbergraph_flammable::K2Node_MakeStruct_ParticleSysParam_2' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Array_Add_ReturnValue_2) == 0x000550, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Array_Add_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x000558, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_RandomBoolWithWeight_ReturnValue) == 0x000560, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_RandomBoolWithWeight_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BooleanAND_ReturnValue_1) == 0x000561, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_RandomBoolWithWeight_ReturnValue_1) == 0x000562, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_RandomBoolWithWeight_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_BooleanAND_ReturnValue_2) == 0x000563, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_getMainGamemode_AsMain_Gamemode) == 0x000568, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_getMainGamemode_AsMain_Gamemode' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_getMainGamemode_AsMain_Gamemode_1) == 0x000570, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_getMainGamemode_AsMain_Gamemode_1' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Array_RemoveItem_ReturnValue) == 0x000578, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Array_RemoveItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_ExecuteUbergraph_flammable, CallFunc_Array_AddUnique_ReturnValue) == 0x00057C, "Member 'Flammable_C_ExecuteUbergraph_flammable::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");

// Function flammable.flammable_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct Flammable_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Flammable_C_ReceiveTick) == 0x000004, "Wrong alignment on Flammable_C_ReceiveTick");
static_assert(sizeof(Flammable_C_ReceiveTick) == 0x000004, "Wrong size on Flammable_C_ReceiveTick");
static_assert(offsetof(Flammable_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'Flammable_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function flammable.flammable_C.des
// 0x0008 (0x0008 - 0x0000)
struct Flammable_C_Des final
{
public:
	class AActor*                                 DestroyedActor;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Flammable_C_Des) == 0x000008, "Wrong alignment on Flammable_C_Des");
static_assert(sizeof(Flammable_C_Des) == 0x000008, "Wrong size on Flammable_C_Des");
static_assert(offsetof(Flammable_C_Des, DestroyedActor) == 0x000000, "Member 'Flammable_C_Des::DestroyedActor' has a wrong offset!");

// Function flammable.flammable_C.ignite_s
// 0x0004 (0x0004 - 0x0000)
struct Flammable_C_Ignite_s final
{
public:
	float                                         Fuel_0;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Flammable_C_Ignite_s) == 0x000004, "Wrong alignment on Flammable_C_Ignite_s");
static_assert(sizeof(Flammable_C_Ignite_s) == 0x000004, "Wrong size on Flammable_C_Ignite_s");
static_assert(offsetof(Flammable_C_Ignite_s, Fuel_0) == 0x000000, "Member 'Flammable_C_Ignite_s::Fuel_0' has a wrong offset!");

// Function flammable.flammable_C.bound
// 0x0080 (0x0080 - 0x0000)
struct Flammable_C_bound final
{
public:
	const class USceneComponent*                  Component_0;                                       // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Origin;                                            // 0x0008(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                BoxExtent;                                         // 0x0014(0x000C)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetComponentBounds_Origin;                // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetComponentBounds_BoxExtent;             // 0x002C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetComponentBounds_SphereRadius;          // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   K2Node_DynamicCast_AsStatic_Mesh_Component;        // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentScale_ReturnValue;         // 0x004C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBoxSphereBounds                       CallFunc_GetBounds_ReturnValue;                    // 0x0058(0x001C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x0074(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Flammable_C_bound) == 0x000008, "Wrong alignment on Flammable_C_bound");
static_assert(sizeof(Flammable_C_bound) == 0x000080, "Wrong size on Flammable_C_bound");
static_assert(offsetof(Flammable_C_bound, Component_0) == 0x000000, "Member 'Flammable_C_bound::Component_0' has a wrong offset!");
static_assert(offsetof(Flammable_C_bound, Origin) == 0x000008, "Member 'Flammable_C_bound::Origin' has a wrong offset!");
static_assert(offsetof(Flammable_C_bound, BoxExtent) == 0x000014, "Member 'Flammable_C_bound::BoxExtent' has a wrong offset!");
static_assert(offsetof(Flammable_C_bound, CallFunc_GetComponentBounds_Origin) == 0x000020, "Member 'Flammable_C_bound::CallFunc_GetComponentBounds_Origin' has a wrong offset!");
static_assert(offsetof(Flammable_C_bound, CallFunc_GetComponentBounds_BoxExtent) == 0x00002C, "Member 'Flammable_C_bound::CallFunc_GetComponentBounds_BoxExtent' has a wrong offset!");
static_assert(offsetof(Flammable_C_bound, CallFunc_GetComponentBounds_SphereRadius) == 0x000038, "Member 'Flammable_C_bound::CallFunc_GetComponentBounds_SphereRadius' has a wrong offset!");
static_assert(offsetof(Flammable_C_bound, K2Node_DynamicCast_AsStatic_Mesh_Component) == 0x000040, "Member 'Flammable_C_bound::K2Node_DynamicCast_AsStatic_Mesh_Component' has a wrong offset!");
static_assert(offsetof(Flammable_C_bound, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'Flammable_C_bound::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Flammable_C_bound, CallFunc_K2_GetComponentScale_ReturnValue) == 0x00004C, "Member 'Flammable_C_bound::CallFunc_K2_GetComponentScale_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_bound, CallFunc_GetBounds_ReturnValue) == 0x000058, "Member 'Flammable_C_bound::CallFunc_GetBounds_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_bound, CallFunc_Multiply_VectorVector_ReturnValue) == 0x000074, "Member 'Flammable_C_bound::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");

// Function flammable.flammable_C.igniteSound
// 0x0038 (0x0038 - 0x0000)
struct Flammable_C_IgniteSound final
{
public:
	struct FVector                                CallFunc_GetActorBounds_Origin;                    // 0x0000(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetActorBounds_BoxExtent;                 // 0x000C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        CallFunc_K2_GetRootComponent_ReturnValue;          // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue;           // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Flammable_C_IgniteSound) == 0x000008, "Wrong alignment on Flammable_C_IgniteSound");
static_assert(sizeof(Flammable_C_IgniteSound) == 0x000038, "Wrong size on Flammable_C_IgniteSound");
static_assert(offsetof(Flammable_C_IgniteSound, CallFunc_GetActorBounds_Origin) == 0x000000, "Member 'Flammable_C_IgniteSound::CallFunc_GetActorBounds_Origin' has a wrong offset!");
static_assert(offsetof(Flammable_C_IgniteSound, CallFunc_GetActorBounds_BoxExtent) == 0x00000C, "Member 'Flammable_C_IgniteSound::CallFunc_GetActorBounds_BoxExtent' has a wrong offset!");
static_assert(offsetof(Flammable_C_IgniteSound, CallFunc_K2_GetRootComponent_ReturnValue) == 0x000018, "Member 'Flammable_C_IgniteSound::CallFunc_K2_GetRootComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_IgniteSound, CallFunc_GetDisplayName_ReturnValue) == 0x000020, "Member 'Flammable_C_IgniteSound::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(Flammable_C_IgniteSound, CallFunc_SpawnSoundAttached_ReturnValue) == 0x000030, "Member 'Flammable_C_IgniteSound::CallFunc_SpawnSoundAttached_ReturnValue' has a wrong offset!");

}

