#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KerfurOmegaV1_Skeleton_AnimBlueprint1

#include "Basic.hpp"

#include "KerfurOmegaV1_Skeleton_AnimBlueprint1_classes.hpp"
#include "KerfurOmegaV1_Skeleton_AnimBlueprint1_parameters.hpp"


namespace SDK
{

// Function kerfurOmegaV1_Skeleton_AnimBlueprint1.kerfurOmegaV1_Skeleton_AnimBlueprint1_C.ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKerfurOmegaV1_Skeleton_AnimBlueprint1_C::ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("kerfurOmegaV1_Skeleton_AnimBlueprint1_C", "ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1");

	Params::KerfurOmegaV1_Skeleton_AnimBlueprint1_C_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function kerfurOmegaV1_Skeleton_AnimBlueprint1.kerfurOmegaV1_Skeleton_AnimBlueprint1_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKerfurOmegaV1_Skeleton_AnimBlueprint1_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("kerfurOmegaV1_Skeleton_AnimBlueprint1_C", "BlueprintUpdateAnimation");

	Params::KerfurOmegaV1_Skeleton_AnimBlueprint1_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function kerfurOmegaV1_Skeleton_AnimBlueprint1.kerfurOmegaV1_Skeleton_AnimBlueprint1_C.EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_84E1E7B54409A06908966BA5165E6874
// (BlueprintEvent)

void UKerfurOmegaV1_Skeleton_AnimBlueprint1_C::EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_84E1E7B54409A06908966BA5165E6874()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("kerfurOmegaV1_Skeleton_AnimBlueprint1_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_84E1E7B54409A06908966BA5165E6874");

	UObject::ProcessEvent(Func, nullptr);
}


// Function kerfurOmegaV1_Skeleton_AnimBlueprint1.kerfurOmegaV1_Skeleton_AnimBlueprint1_C.EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_B876763F4596AA82E0301380C67BF9A9
// (BlueprintEvent)

void UKerfurOmegaV1_Skeleton_AnimBlueprint1_C::EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_B876763F4596AA82E0301380C67BF9A9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("kerfurOmegaV1_Skeleton_AnimBlueprint1_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_B876763F4596AA82E0301380C67BF9A9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function kerfurOmegaV1_Skeleton_AnimBlueprint1.kerfurOmegaV1_Skeleton_AnimBlueprint1_C.EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_81CB01484A80492D9890758AB7F90E21
// (BlueprintEvent)

void UKerfurOmegaV1_Skeleton_AnimBlueprint1_C::EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_81CB01484A80492D9890758AB7F90E21()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("kerfurOmegaV1_Skeleton_AnimBlueprint1_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_81CB01484A80492D9890758AB7F90E21");

	UObject::ProcessEvent(Func, nullptr);
}


// Function kerfurOmegaV1_Skeleton_AnimBlueprint1.kerfurOmegaV1_Skeleton_AnimBlueprint1_C.EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_AFCBED434818B2643729DD9F658D39F7
// (BlueprintEvent)

void UKerfurOmegaV1_Skeleton_AnimBlueprint1_C::EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_AFCBED434818B2643729DD9F658D39F7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("kerfurOmegaV1_Skeleton_AnimBlueprint1_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_AFCBED434818B2643729DD9F658D39F7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function kerfurOmegaV1_Skeleton_AnimBlueprint1.kerfurOmegaV1_Skeleton_AnimBlueprint1_C.EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_AFEBD51D428584A243335AB175BB8FB6
// (BlueprintEvent)

void UKerfurOmegaV1_Skeleton_AnimBlueprint1_C::EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_AFEBD51D428584A243335AB175BB8FB6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("kerfurOmegaV1_Skeleton_AnimBlueprint1_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_AFEBD51D428584A243335AB175BB8FB6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function kerfurOmegaV1_Skeleton_AnimBlueprint1.kerfurOmegaV1_Skeleton_AnimBlueprint1_C.EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_6A5C71CD416E8B4543E151979DC21A15
// (BlueprintEvent)

void UKerfurOmegaV1_Skeleton_AnimBlueprint1_C::EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_6A5C71CD416E8B4543E151979DC21A15()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("kerfurOmegaV1_Skeleton_AnimBlueprint1_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_6A5C71CD416E8B4543E151979DC21A15");

	UObject::ProcessEvent(Func, nullptr);
}


// Function kerfurOmegaV1_Skeleton_AnimBlueprint1.kerfurOmegaV1_Skeleton_AnimBlueprint1_C.EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_24D4041746D03EC783C1538CC09714FF
// (BlueprintEvent)

void UKerfurOmegaV1_Skeleton_AnimBlueprint1_C::EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_24D4041746D03EC783C1538CC09714FF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("kerfurOmegaV1_Skeleton_AnimBlueprint1_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_kerfurOmegaV1_Skeleton_AnimBlueprint1_AnimGraphNode_ModifyBone_24D4041746D03EC783C1538CC09714FF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function kerfurOmegaV1_Skeleton_AnimBlueprint1.kerfurOmegaV1_Skeleton_AnimBlueprint1_C.randrot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   Max                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRotator                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

struct FRotator UKerfurOmegaV1_Skeleton_AnimBlueprint1_C::Randrot(float Max)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("kerfurOmegaV1_Skeleton_AnimBlueprint1_C", "randrot");

	Params::KerfurOmegaV1_Skeleton_AnimBlueprint1_C_Randrot Parms{};

	Parms.Max = Max;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function kerfurOmegaV1_Skeleton_AnimBlueprint1.kerfurOmegaV1_Skeleton_AnimBlueprint1_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UKerfurOmegaV1_Skeleton_AnimBlueprint1_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("kerfurOmegaV1_Skeleton_AnimBlueprint1_C", "AnimGraph");

	Params::KerfurOmegaV1_Skeleton_AnimBlueprint1_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

