#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_thermometer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Prop_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass prop_thermometer.prop_thermometer_C
// 0x0008 (0x0360 - 0x0358)
class AProp_thermometer_C final : public AProp_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Prop_thermometer_C;                 // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_prop_thermometer(int32 EntryPoint);
	void PlayerHandUse_RMB(class AMainPlayer_C* Player);
	void PlayerHandUse_LMB(class AMainPlayer_C* Player);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"prop_thermometer_C">();
	}
	static class AProp_thermometer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_thermometer_C>();
	}
};
static_assert(alignof(AProp_thermometer_C) == 0x000008, "Wrong alignment on AProp_thermometer_C");
static_assert(sizeof(AProp_thermometer_C) == 0x000360, "Wrong size on AProp_thermometer_C");
static_assert(offsetof(AProp_thermometer_C, UberGraphFrame_Prop_thermometer_C) == 0x000358, "Member 'AProp_thermometer_C::UberGraphFrame_Prop_thermometer_C' has a wrong offset!");

}

