#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_briefcase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Prop_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass prop_briefcase.prop_briefcase_C
// 0x0008 (0x0360 - 0x0358)
class AProp_briefcase_C final : public AProp_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Prop_briefcase_C;                   // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_prop_briefcase(int32 EntryPoint);
	void CustomEvent_0();
	void ReceiveBeginPlay();
	void IgnoreSave(bool* Param_IgnoreSave_0);
	void GatherDataFromKey(bool* Gather);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"prop_briefcase_C">();
	}
	static class AProp_briefcase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_briefcase_C>();
	}
};
static_assert(alignof(AProp_briefcase_C) == 0x000008, "Wrong alignment on AProp_briefcase_C");
static_assert(sizeof(AProp_briefcase_C) == 0x000360, "Wrong size on AProp_briefcase_C");
static_assert(offsetof(AProp_briefcase_C, UberGraphFrame_Prop_briefcase_C) == 0x000358, "Member 'AProp_briefcase_C::UberGraphFrame_Prop_briefcase_C' has a wrong offset!");

}

