#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_rack

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function prop_rack.prop_rack_C.ExecuteUbergraph_prop_rack
// 0x0690 (0x0690 - 0x0000)
struct Prop_rack_C_ExecuteUbergraph_prop_rack final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_8;                   // 0x0014(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_7;                   // 0x001C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_1;            // 0x0024(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_6;                   // 0x0034(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_2;            // 0x003C(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_5;                   // 0x004C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_3;            // 0x0054(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   Temp_name_Variable;                                // 0x0064(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_4;            // 0x006C(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          K2Node_SwitchName_CmpSuccess;                      // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7D[0x3];                                       // 0x007D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_CustomEvent_NotifyName_4;                   // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_3;                   // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_5;            // 0x0090(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_2;                   // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_6;            // 0x00A8(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_1;                   // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_7;            // 0x00C0(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName;                     // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_8;            // 0x00D8(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   Temp_name_Variable_1;                              // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue; // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F9[0x7];                                       // 0x00F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0100(0x0010)(ConstParm, ReferenceParm)
	TArray<class AActor*>                         Temp_object_Variable_1;                            // 0x0110(0x0010)(ConstParm, ReferenceParm)
	class AMainPlayer_C*                          K2Node_Event_player_2;                             // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<EObjectTypeQuery>                      CallFunc_obj_statDyn_obj;                          // 0x0128(0x0010)(ReferenceParm)
	struct FVector                                CallFunc_arm_start;                                // 0x0138(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_arm_end;                                  // 0x0144(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_arm_rotation;                             // 0x0150(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AMainPlayer_C*                          K2Node_Event_player_1;                             // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingleForObjects_OutHit;         // 0x0168(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingleForObjects_ReturnValue;    // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F1[0x7];                                      // 0x01F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1; // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x0201(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_202[0x2];                                      // 0x0202(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0204(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0208(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x020C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0218(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0224(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0230(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_23C[0x4];                                      // 0x023C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0240(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0250(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0260(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x0264(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0268(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x026C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0278(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSimulatingPhysics_ReturnValue;          // 0x0284(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ECollisionChannel                             CallFunc_GetCollisionObjectType_ReturnValue;       // 0x0285(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0286(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0287(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AMurderKerfuroDig_C*                    K2Node_DynamicCast_AsMurder_Kerfuro_Dig;           // 0x0288(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_291[0x7];                                      // 0x0291(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActorChipPile_C*                       K2Node_DynamicCast_AsActor_Chip_Pile;              // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x02A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x02A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_1;    // 0x02A2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A3[0x1];                                      // 0x02A3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_SelectInt_ReturnValue;                    // 0x02A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_2;    // 0x02A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_3;    // 0x02A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2AA[0x2];                                      // 0x02AA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_SelectInt_ReturnValue_1;                  // 0x02AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x02B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x02B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x02B3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x02B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x02B5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B6[0x2];                                      // 0x02B6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetActorForwardVector_ReturnValue;        // 0x02B8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_9;                   // 0x02C4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Cross_VectorVector_ReturnValue;           // 0x02CC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotationFromAxes_ReturnValue;         // 0x02D8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E4[0xC];                                      // 0x02E4(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x02F0(0x0030)(IsPlainOldData, NoDestructor)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_9;            // 0x0320(0x0010)(ZeroConstructor, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0330(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ADirthole_rack_C*                       CallFunc_FinishSpawningActor_ReturnValue;          // 0x0338(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMainPlayer_C*                          K2Node_Event_player;                               // 0x0340(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_hit;                                  // 0x0348(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	struct FVector                                CallFunc_GetVelocity_ReturnValue;                  // 0x03D0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VSize_ReturnValue;                        // 0x03DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x03E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x03E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3E2[0xE];                                      // 0x03E2(0x000E)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x03F0(0x0030)(IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_TLerp_ReturnValue;                        // 0x0420(0x0030)(IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0450(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Dot_VectorVector_ReturnValue;             // 0x045C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldTransform_SweepHitResult;      // 0x0460(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x04E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x04E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4EA[0x6];                                      // 0x04EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue_1;     // 0x04F0(0x0030)(IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x0520(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_521[0x3];                                      // 0x0521(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetActorRightVector_ReturnValue;          // 0x0524(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0530(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_53C[0x4];                                      // 0x053C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EObjectTypeQuery>                      CallFunc_obj_pawn_obj;                             // 0x0540(0x0010)(ReferenceParm)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0550(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x055C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_SphereTraceSingleForObjects_OutHit;       // 0x0568(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_SphereTraceSingleForObjects_ReturnValue;  // 0x05F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit_1;            // 0x05F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap_1;         // 0x05F2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5F3[0x1];                                      // 0x05F3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time_1;                    // 0x05F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance_1;                // 0x05F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location_1;                // 0x05FC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint_1;             // 0x0608(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal_1;                  // 0x0614(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal_1;            // 0x0620(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62C[0x4];                                      // 0x062C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat_1;                 // 0x0630(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor_1;                // 0x0638(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent_1;            // 0x0640(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName_1;             // 0x0648(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem_1;                 // 0x0650(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex_1;            // 0x0654(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex_1;               // 0x0658(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart_1;              // 0x065C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd_1;                // 0x0668(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_674[0x4];                                      // 0x0674(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AMainPlayer_C*                          K2Node_DynamicCast_AsMain_Player;                  // 0x0678(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0680(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Prop_rack_C_ExecuteUbergraph_prop_rack) == 0x000010, "Wrong alignment on Prop_rack_C_ExecuteUbergraph_prop_rack");
static_assert(sizeof(Prop_rack_C_ExecuteUbergraph_prop_rack) == 0x000690, "Wrong size on Prop_rack_C_ExecuteUbergraph_prop_rack");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, EntryPoint) == 0x000000, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::EntryPoint' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CustomEvent_NotifyName_8) == 0x000014, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CustomEvent_NotifyName_8' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CustomEvent_NotifyName_7) == 0x00001C, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CustomEvent_NotifyName_7' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CreateDelegate_OutputDelegate_1) == 0x000024, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CustomEvent_NotifyName_6) == 0x000034, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CustomEvent_NotifyName_6' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CreateDelegate_OutputDelegate_2) == 0x00003C, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CustomEvent_NotifyName_5) == 0x00004C, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CustomEvent_NotifyName_5' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CreateDelegate_OutputDelegate_3) == 0x000054, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, Temp_name_Variable) == 0x000064, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CreateDelegate_OutputDelegate_4) == 0x00006C, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_SwitchName_CmpSuccess) == 0x00007C, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_SwitchName_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CustomEvent_NotifyName_4) == 0x000080, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CustomEvent_NotifyName_4' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CustomEvent_NotifyName_3) == 0x000088, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CustomEvent_NotifyName_3' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CreateDelegate_OutputDelegate_5) == 0x000090, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CustomEvent_NotifyName_2) == 0x0000A0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CustomEvent_NotifyName_2' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CreateDelegate_OutputDelegate_6) == 0x0000A8, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CustomEvent_NotifyName_1) == 0x0000B8, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CustomEvent_NotifyName_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CreateDelegate_OutputDelegate_7) == 0x0000C0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CustomEvent_NotifyName) == 0x0000D0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CustomEvent_NotifyName' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CreateDelegate_OutputDelegate_8) == 0x0000D8, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, Temp_name_Variable_1) == 0x0000E8, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::Temp_name_Variable_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue) == 0x0000F0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_IsValid_ReturnValue) == 0x0000F8, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, Temp_object_Variable) == 0x000100, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, Temp_object_Variable_1) == 0x000110, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_Event_player_2) == 0x000120, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_Event_player_2' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_obj_statDyn_obj) == 0x000128, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_obj_statDyn_obj' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_arm_start) == 0x000138, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_arm_start' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_arm_end) == 0x000144, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_arm_end' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_arm_rotation) == 0x000150, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_arm_rotation' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_Event_player_1) == 0x000160, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_Event_player_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_LineTraceSingleForObjects_OutHit) == 0x000168, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_LineTraceSingleForObjects_OutHit' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_LineTraceSingleForObjects_ReturnValue) == 0x0001F0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_LineTraceSingleForObjects_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1) == 0x0001F8, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_bBlockingHit) == 0x000200, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_bInitialOverlap) == 0x000201, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_Time) == 0x000204, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_Distance) == 0x000208, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_Location) == 0x00020C, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_ImpactPoint) == 0x000218, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_Normal) == 0x000224, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_ImpactNormal) == 0x000230, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_PhysMat) == 0x000240, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_HitActor) == 0x000248, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_HitComponent) == 0x000250, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_HitBoneName) == 0x000258, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_HitItem) == 0x000260, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_ElementIndex) == 0x000264, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_FaceIndex) == 0x000268, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_TraceStart) == 0x00026C, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_TraceEnd) == 0x000278, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_IsSimulatingPhysics_ReturnValue) == 0x000284, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_IsSimulatingPhysics_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_GetCollisionObjectType_ReturnValue) == 0x000285, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_GetCollisionObjectType_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_Not_PreBool_ReturnValue) == 0x000286, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000287, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_DynamicCast_AsMurder_Kerfuro_Dig) == 0x000288, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_DynamicCast_AsMurder_Kerfuro_Dig' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_DynamicCast_bSuccess) == 0x000290, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_DynamicCast_AsActor_Chip_Pile) == 0x000298, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_DynamicCast_AsActor_Chip_Pile' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_DynamicCast_bSuccess_1) == 0x0002A0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0002A1, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_EqualEqual_ObjectObject_ReturnValue_1) == 0x0002A2, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_EqualEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_SelectInt_ReturnValue) == 0x0002A4, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_SelectInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_EqualEqual_ObjectObject_ReturnValue_2) == 0x0002A8, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_EqualEqual_ObjectObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_EqualEqual_ObjectObject_ReturnValue_3) == 0x0002A9, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_EqualEqual_ObjectObject_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_SelectInt_ReturnValue_1) == 0x0002AC, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_SelectInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BooleanOR_ReturnValue) == 0x0002B0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BooleanOR_ReturnValue_1) == 0x0002B1, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BooleanOR_ReturnValue_2) == 0x0002B2, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BooleanAND_ReturnValue) == 0x0002B3, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BooleanAND_ReturnValue_1) == 0x0002B4, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_IsValid_ReturnValue_1) == 0x0002B5, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_GetActorForwardVector_ReturnValue) == 0x0002B8, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_GetActorForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CustomEvent_NotifyName_9) == 0x0002C4, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CustomEvent_NotifyName_9' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_Cross_VectorVector_ReturnValue) == 0x0002CC, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_Cross_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_MakeRotationFromAxes_ReturnValue) == 0x0002D8, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_MakeRotationFromAxes_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_MakeTransform_ReturnValue) == 0x0002F0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_CreateDelegate_OutputDelegate_9) == 0x000320, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_CreateDelegate_OutputDelegate_9' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000330, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_FinishSpawningActor_ReturnValue) == 0x000338, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_Event_player) == 0x000340, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_Event_player' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_Event_hit) == 0x000348, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_Event_hit' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_GetVelocity_ReturnValue) == 0x0003D0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_GetVelocity_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_VSize_ReturnValue) == 0x0003DC, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x0003E0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_Not_PreBool_ReturnValue_1) == 0x0003E1, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x0003F0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_TLerp_ReturnValue) == 0x000420, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_TLerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_GetForwardVector_ReturnValue) == 0x000450, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_Dot_VectorVector_ReturnValue) == 0x00045C, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_Dot_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_K2_SetWorldTransform_SweepHitResult) == 0x000460, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_K2_SetWorldTransform_SweepHitResult' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x0004E8, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BooleanAND_ReturnValue_2) == 0x0004E9, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_K2_GetComponentToWorld_ReturnValue_1) == 0x0004F0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_K2_GetComponentToWorld_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BooleanAND_ReturnValue_3) == 0x000520, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BooleanAND_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_GetActorRightVector_ReturnValue) == 0x000524, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_GetActorRightVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000530, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_obj_pawn_obj) == 0x000540, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_obj_pawn_obj' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000550, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x00055C, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_SphereTraceSingleForObjects_OutHit) == 0x000568, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_SphereTraceSingleForObjects_OutHit' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_SphereTraceSingleForObjects_ReturnValue) == 0x0005F0, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_SphereTraceSingleForObjects_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_bBlockingHit_1) == 0x0005F1, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_bBlockingHit_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_bInitialOverlap_1) == 0x0005F2, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_bInitialOverlap_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_Time_1) == 0x0005F4, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_Time_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_Distance_1) == 0x0005F8, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_Distance_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_Location_1) == 0x0005FC, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_Location_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_ImpactPoint_1) == 0x000608, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_ImpactPoint_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_Normal_1) == 0x000614, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_Normal_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_ImpactNormal_1) == 0x000620, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_ImpactNormal_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_PhysMat_1) == 0x000630, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_PhysMat_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_HitActor_1) == 0x000638, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_HitActor_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_HitComponent_1) == 0x000640, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_HitComponent_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_HitBoneName_1) == 0x000648, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_HitBoneName_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_HitItem_1) == 0x000650, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_HitItem_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_ElementIndex_1) == 0x000654, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_ElementIndex_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_FaceIndex_1) == 0x000658, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_FaceIndex_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_TraceStart_1) == 0x00065C, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_TraceStart_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, CallFunc_BreakHitResult_TraceEnd_1) == 0x000668, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::CallFunc_BreakHitResult_TraceEnd_1' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_DynamicCast_AsMain_Player) == 0x000678, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_DynamicCast_AsMain_Player' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_ExecuteUbergraph_prop_rack, K2Node_DynamicCast_bSuccess_2) == 0x000680, "Member 'Prop_rack_C_ExecuteUbergraph_prop_rack::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");

// Function prop_rack.prop_rack_C.OnCompleted_C4DD4A4849ECBCBBA470EE92776983F3
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_OnCompleted_C4DD4A4849ECBCBBA470EE92776983F3 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_OnCompleted_C4DD4A4849ECBCBBA470EE92776983F3) == 0x000004, "Wrong alignment on Prop_rack_C_OnCompleted_C4DD4A4849ECBCBBA470EE92776983F3");
static_assert(sizeof(Prop_rack_C_OnCompleted_C4DD4A4849ECBCBBA470EE92776983F3) == 0x000008, "Wrong size on Prop_rack_C_OnCompleted_C4DD4A4849ECBCBBA470EE92776983F3");
static_assert(offsetof(Prop_rack_C_OnCompleted_C4DD4A4849ECBCBBA470EE92776983F3, NotifyName) == 0x000000, "Member 'Prop_rack_C_OnCompleted_C4DD4A4849ECBCBBA470EE92776983F3::NotifyName' has a wrong offset!");

// Function prop_rack.prop_rack_C.OnBlendOut_C4DD4A4849ECBCBBA470EE92776983F3
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_OnBlendOut_C4DD4A4849ECBCBBA470EE92776983F3 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_OnBlendOut_C4DD4A4849ECBCBBA470EE92776983F3) == 0x000004, "Wrong alignment on Prop_rack_C_OnBlendOut_C4DD4A4849ECBCBBA470EE92776983F3");
static_assert(sizeof(Prop_rack_C_OnBlendOut_C4DD4A4849ECBCBBA470EE92776983F3) == 0x000008, "Wrong size on Prop_rack_C_OnBlendOut_C4DD4A4849ECBCBBA470EE92776983F3");
static_assert(offsetof(Prop_rack_C_OnBlendOut_C4DD4A4849ECBCBBA470EE92776983F3, NotifyName) == 0x000000, "Member 'Prop_rack_C_OnBlendOut_C4DD4A4849ECBCBBA470EE92776983F3::NotifyName' has a wrong offset!");

// Function prop_rack.prop_rack_C.OnInterrupted_C4DD4A4849ECBCBBA470EE92776983F3
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_OnInterrupted_C4DD4A4849ECBCBBA470EE92776983F3 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_OnInterrupted_C4DD4A4849ECBCBBA470EE92776983F3) == 0x000004, "Wrong alignment on Prop_rack_C_OnInterrupted_C4DD4A4849ECBCBBA470EE92776983F3");
static_assert(sizeof(Prop_rack_C_OnInterrupted_C4DD4A4849ECBCBBA470EE92776983F3) == 0x000008, "Wrong size on Prop_rack_C_OnInterrupted_C4DD4A4849ECBCBBA470EE92776983F3");
static_assert(offsetof(Prop_rack_C_OnInterrupted_C4DD4A4849ECBCBBA470EE92776983F3, NotifyName) == 0x000000, "Member 'Prop_rack_C_OnInterrupted_C4DD4A4849ECBCBBA470EE92776983F3::NotifyName' has a wrong offset!");

// Function prop_rack.prop_rack_C.OnNotifyBegin_C4DD4A4849ECBCBBA470EE92776983F3
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_OnNotifyBegin_C4DD4A4849ECBCBBA470EE92776983F3 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_OnNotifyBegin_C4DD4A4849ECBCBBA470EE92776983F3) == 0x000004, "Wrong alignment on Prop_rack_C_OnNotifyBegin_C4DD4A4849ECBCBBA470EE92776983F3");
static_assert(sizeof(Prop_rack_C_OnNotifyBegin_C4DD4A4849ECBCBBA470EE92776983F3) == 0x000008, "Wrong size on Prop_rack_C_OnNotifyBegin_C4DD4A4849ECBCBBA470EE92776983F3");
static_assert(offsetof(Prop_rack_C_OnNotifyBegin_C4DD4A4849ECBCBBA470EE92776983F3, NotifyName) == 0x000000, "Member 'Prop_rack_C_OnNotifyBegin_C4DD4A4849ECBCBBA470EE92776983F3::NotifyName' has a wrong offset!");

// Function prop_rack.prop_rack_C.OnNotifyEnd_C4DD4A4849ECBCBBA470EE92776983F3
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_OnNotifyEnd_C4DD4A4849ECBCBBA470EE92776983F3 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_OnNotifyEnd_C4DD4A4849ECBCBBA470EE92776983F3) == 0x000004, "Wrong alignment on Prop_rack_C_OnNotifyEnd_C4DD4A4849ECBCBBA470EE92776983F3");
static_assert(sizeof(Prop_rack_C_OnNotifyEnd_C4DD4A4849ECBCBBA470EE92776983F3) == 0x000008, "Wrong size on Prop_rack_C_OnNotifyEnd_C4DD4A4849ECBCBBA470EE92776983F3");
static_assert(offsetof(Prop_rack_C_OnNotifyEnd_C4DD4A4849ECBCBBA470EE92776983F3, NotifyName) == 0x000000, "Member 'Prop_rack_C_OnNotifyEnd_C4DD4A4849ECBCBBA470EE92776983F3::NotifyName' has a wrong offset!");

// Function prop_rack.prop_rack_C.OnCompleted_0F7346AF4815D1B767E7E1B865F06C02
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_OnCompleted_0F7346AF4815D1B767E7E1B865F06C02 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_OnCompleted_0F7346AF4815D1B767E7E1B865F06C02) == 0x000004, "Wrong alignment on Prop_rack_C_OnCompleted_0F7346AF4815D1B767E7E1B865F06C02");
static_assert(sizeof(Prop_rack_C_OnCompleted_0F7346AF4815D1B767E7E1B865F06C02) == 0x000008, "Wrong size on Prop_rack_C_OnCompleted_0F7346AF4815D1B767E7E1B865F06C02");
static_assert(offsetof(Prop_rack_C_OnCompleted_0F7346AF4815D1B767E7E1B865F06C02, NotifyName) == 0x000000, "Member 'Prop_rack_C_OnCompleted_0F7346AF4815D1B767E7E1B865F06C02::NotifyName' has a wrong offset!");

// Function prop_rack.prop_rack_C.OnBlendOut_0F7346AF4815D1B767E7E1B865F06C02
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_OnBlendOut_0F7346AF4815D1B767E7E1B865F06C02 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_OnBlendOut_0F7346AF4815D1B767E7E1B865F06C02) == 0x000004, "Wrong alignment on Prop_rack_C_OnBlendOut_0F7346AF4815D1B767E7E1B865F06C02");
static_assert(sizeof(Prop_rack_C_OnBlendOut_0F7346AF4815D1B767E7E1B865F06C02) == 0x000008, "Wrong size on Prop_rack_C_OnBlendOut_0F7346AF4815D1B767E7E1B865F06C02");
static_assert(offsetof(Prop_rack_C_OnBlendOut_0F7346AF4815D1B767E7E1B865F06C02, NotifyName) == 0x000000, "Member 'Prop_rack_C_OnBlendOut_0F7346AF4815D1B767E7E1B865F06C02::NotifyName' has a wrong offset!");

// Function prop_rack.prop_rack_C.OnInterrupted_0F7346AF4815D1B767E7E1B865F06C02
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_OnInterrupted_0F7346AF4815D1B767E7E1B865F06C02 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_OnInterrupted_0F7346AF4815D1B767E7E1B865F06C02) == 0x000004, "Wrong alignment on Prop_rack_C_OnInterrupted_0F7346AF4815D1B767E7E1B865F06C02");
static_assert(sizeof(Prop_rack_C_OnInterrupted_0F7346AF4815D1B767E7E1B865F06C02) == 0x000008, "Wrong size on Prop_rack_C_OnInterrupted_0F7346AF4815D1B767E7E1B865F06C02");
static_assert(offsetof(Prop_rack_C_OnInterrupted_0F7346AF4815D1B767E7E1B865F06C02, NotifyName) == 0x000000, "Member 'Prop_rack_C_OnInterrupted_0F7346AF4815D1B767E7E1B865F06C02::NotifyName' has a wrong offset!");

// Function prop_rack.prop_rack_C.OnNotifyBegin_0F7346AF4815D1B767E7E1B865F06C02
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_OnNotifyBegin_0F7346AF4815D1B767E7E1B865F06C02 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_OnNotifyBegin_0F7346AF4815D1B767E7E1B865F06C02) == 0x000004, "Wrong alignment on Prop_rack_C_OnNotifyBegin_0F7346AF4815D1B767E7E1B865F06C02");
static_assert(sizeof(Prop_rack_C_OnNotifyBegin_0F7346AF4815D1B767E7E1B865F06C02) == 0x000008, "Wrong size on Prop_rack_C_OnNotifyBegin_0F7346AF4815D1B767E7E1B865F06C02");
static_assert(offsetof(Prop_rack_C_OnNotifyBegin_0F7346AF4815D1B767E7E1B865F06C02, NotifyName) == 0x000000, "Member 'Prop_rack_C_OnNotifyBegin_0F7346AF4815D1B767E7E1B865F06C02::NotifyName' has a wrong offset!");

// Function prop_rack.prop_rack_C.OnNotifyEnd_0F7346AF4815D1B767E7E1B865F06C02
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_OnNotifyEnd_0F7346AF4815D1B767E7E1B865F06C02 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_OnNotifyEnd_0F7346AF4815D1B767E7E1B865F06C02) == 0x000004, "Wrong alignment on Prop_rack_C_OnNotifyEnd_0F7346AF4815D1B767E7E1B865F06C02");
static_assert(sizeof(Prop_rack_C_OnNotifyEnd_0F7346AF4815D1B767E7E1B865F06C02) == 0x000008, "Wrong size on Prop_rack_C_OnNotifyEnd_0F7346AF4815D1B767E7E1B865F06C02");
static_assert(offsetof(Prop_rack_C_OnNotifyEnd_0F7346AF4815D1B767E7E1B865F06C02, NotifyName) == 0x000000, "Member 'Prop_rack_C_OnNotifyEnd_0F7346AF4815D1B767E7E1B865F06C02::NotifyName' has a wrong offset!");

// Function prop_rack.prop_rack_C.steppedOn
// 0x0090 (0x0090 - 0x0000)
struct Prop_rack_C_SteppedOn final
{
public:
	class AMainPlayer_C*                          Player_0;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit_0;                                             // 0x0008(0x0088)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Prop_rack_C_SteppedOn) == 0x000008, "Wrong alignment on Prop_rack_C_SteppedOn");
static_assert(sizeof(Prop_rack_C_SteppedOn) == 0x000090, "Wrong size on Prop_rack_C_SteppedOn");
static_assert(offsetof(Prop_rack_C_SteppedOn, Player_0) == 0x000000, "Member 'Prop_rack_C_SteppedOn::Player_0' has a wrong offset!");
static_assert(offsetof(Prop_rack_C_SteppedOn, Hit_0) == 0x000008, "Member 'Prop_rack_C_SteppedOn::Hit_0' has a wrong offset!");

// Function prop_rack.prop_rack_C.playerHandRelease_RMB
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_PlayerHandRelease_RMB final
{
public:
	class AMainPlayer_C*                          Player_0;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_PlayerHandRelease_RMB) == 0x000008, "Wrong alignment on Prop_rack_C_PlayerHandRelease_RMB");
static_assert(sizeof(Prop_rack_C_PlayerHandRelease_RMB) == 0x000008, "Wrong size on Prop_rack_C_PlayerHandRelease_RMB");
static_assert(offsetof(Prop_rack_C_PlayerHandRelease_RMB, Player_0) == 0x000000, "Member 'Prop_rack_C_PlayerHandRelease_RMB::Player_0' has a wrong offset!");

// Function prop_rack.prop_rack_C.playerHandUse_RMB
// 0x0008 (0x0008 - 0x0000)
struct Prop_rack_C_PlayerHandUse_RMB final
{
public:
	class AMainPlayer_C*                          Player_0;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_rack_C_PlayerHandUse_RMB) == 0x000008, "Wrong alignment on Prop_rack_C_PlayerHandUse_RMB");
static_assert(sizeof(Prop_rack_C_PlayerHandUse_RMB) == 0x000008, "Wrong size on Prop_rack_C_PlayerHandUse_RMB");
static_assert(offsetof(Prop_rack_C_PlayerHandUse_RMB, Player_0) == 0x000000, "Member 'Prop_rack_C_PlayerHandUse_RMB::Player_0' has a wrong offset!");

}

