#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_doughball

#include "Basic.hpp"

#include "Enum_interactionActions_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Struct_food_structs.hpp"
#include "Struct_prop3_structs.hpp"


namespace SDK::Params
{

// Function prop_doughball.prop_doughball_C.ExecuteUbergraph_prop_doughball
// 0x0420 (0x0420 - 0x0000)
struct Prop_doughball_C_ExecuteUbergraph_prop_doughball final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_1;           // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_2;           // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_3;           // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_4;                               // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_propToObject_ReturnValue;                 // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_food                           CallFunc_propToObject_foodData;                    // 0x003C(0x001C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_propToObject_object;                      // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_propToObject_isFood;                      // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_prop3                          CallFunc_propToObject_fuckYouRetard;               // 0x0068(0x0080)(HasGetValueTypeHash)
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_4;           // 0x00E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_EA[0x2];                                       // 0x00EA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable;                                // 0x00F0(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_5;                               // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable_1;                              // 0x00FC(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_propToObject_ReturnValue_1;               // 0x0104(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_105[0x3];                                      // 0x0105(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_food                           CallFunc_propToObject_foodData_1;                  // 0x0108(0x001C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_124[0x4];                                      // 0x0124(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_propToObject_object_1;                    // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_propToObject_isFood_1;                    // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_131[0x7];                                      // 0x0131(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_prop3                          CallFunc_propToObject_fuckYouRetard_1;             // 0x0138(0x0080)(HasGetValueTypeHash)
	bool                                          CallFunc_IsValidClass_ReturnValue_1;               // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1B9[0x3];                                      // 0x01B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   Temp_name_Variable_2;                              // 0x01BC(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable_3;                              // 0x01C4(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_6;                               // 0x01CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMainPlayer_C*                          K2Node_Event_player;                               // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_hit;                                  // 0x01D8(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	Enum_interactionActions                       K2Node_Event_action;                               // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_261[0x3];                                      // 0x0261(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_7;                               // 0x0264(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_5;           // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_269[0x3];                                      // 0x0269(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x026C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0270(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_271[0x3];                                      // 0x0271(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0274(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetActorScale3D_ReturnValue;              // 0x0280(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x028C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X;                            // 0x0298(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x029C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x02A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A4[0xC];                                      // 0x02A4(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x02B0(0x0030)(IsPlainOldData, NoDestructor)
	float                                         CallFunc_MultiplyMultiply_FloatFloat_ReturnValue;  // 0x02E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2E4[0x4];                                      // 0x02E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x02E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x02F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2F4[0x4];                                      // 0x02F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue;          // 0x02F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Round_ReturnValue;                        // 0x0300(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_304[0x4];                                      // 0x0304(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IInt_player_C>         K2Node_DynamicCast_AsInt_Player;                   // 0x0308(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0318(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_319[0x3];                                      // 0x0319(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x031C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AProp_C*                                CallFunc_asProp_return;                            // 0x0320(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_6;           // 0x0328(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_329[0x7];                                      // 0x0329(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x0330(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0340(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_344[0x4];                                      // 0x0344(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1; // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0350(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MultiplyMultiply_FloatFloat_ReturnValue_1; // 0x0354(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AProp_C*                                CallFunc_FinishSpawningActor_ReturnValue_1;        // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_FloatToVector_ReturnValue;           // 0x0360(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_36C[0x4];                                      // 0x036C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2; // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AProp_food_C*                           CallFunc_FinishSpawningActor_ReturnValue_2;        // 0x0378(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0380(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_38C[0x4];                                      // 0x038C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue_1;              // 0x0390(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_3; // 0x03C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_4; // 0x03C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue_3;        // 0x03D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IInt_player_C>         K2Node_DynamicCast_AsInt_Player_1;                 // 0x03D8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x03E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3E9[0x7];                                      // 0x03E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AProp_food_C*                           CallFunc_FinishSpawningActor_ReturnValue_4;        // 0x03F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AProp_C*                                CallFunc_asProp_return_1;                          // 0x03F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_5; // 0x0400(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AProp_C*                                CallFunc_FinishSpawningActor_ReturnValue_5;        // 0x0408(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue_1;          // 0x0410(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_doughball_C_ExecuteUbergraph_prop_doughball) == 0x000010, "Wrong alignment on Prop_doughball_C_ExecuteUbergraph_prop_doughball");
static_assert(sizeof(Prop_doughball_C_ExecuteUbergraph_prop_doughball) == 0x000420, "Wrong size on Prop_doughball_C_ExecuteUbergraph_prop_doughball");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, EntryPoint) == 0x000000, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::EntryPoint' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_int_Variable) == 0x000004, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000008, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Add_IntInt_ReturnValue) == 0x00000C, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_int_Variable_1) == 0x000010, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_LessEqual_IntInt_ReturnValue_1) == 0x000014, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_LessEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Add_IntInt_ReturnValue_1) == 0x000018, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_int_Variable_2) == 0x00001C, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_LessEqual_IntInt_ReturnValue_2) == 0x000020, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_LessEqual_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Add_IntInt_ReturnValue_2) == 0x000024, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_int_Variable_3) == 0x000028, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_int_Variable_3' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_LessEqual_IntInt_ReturnValue_3) == 0x00002C, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_LessEqual_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Add_IntInt_ReturnValue_3) == 0x000030, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_int_Variable_4) == 0x000034, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_int_Variable_4' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_propToObject_ReturnValue) == 0x000038, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_propToObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_propToObject_foodData) == 0x00003C, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_propToObject_foodData' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_propToObject_object) == 0x000058, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_propToObject_object' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_propToObject_isFood) == 0x000060, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_propToObject_isFood' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_propToObject_fuckYouRetard) == 0x000068, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_propToObject_fuckYouRetard' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_IsValidClass_ReturnValue) == 0x0000E8, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_IsValidClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_LessEqual_IntInt_ReturnValue_4) == 0x0000E9, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_LessEqual_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Add_IntInt_ReturnValue_4) == 0x0000EC, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_name_Variable) == 0x0000F0, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_int_Variable_5) == 0x0000F8, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_int_Variable_5' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_name_Variable_1) == 0x0000FC, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_name_Variable_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_propToObject_ReturnValue_1) == 0x000104, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_propToObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_propToObject_foodData_1) == 0x000108, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_propToObject_foodData_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_propToObject_object_1) == 0x000128, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_propToObject_object_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_propToObject_isFood_1) == 0x000130, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_propToObject_isFood_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_propToObject_fuckYouRetard_1) == 0x000138, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_propToObject_fuckYouRetard_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_IsValidClass_ReturnValue_1) == 0x0001B8, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_IsValidClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_name_Variable_2) == 0x0001BC, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_name_Variable_2' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_name_Variable_3) == 0x0001C4, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_name_Variable_3' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_int_Variable_6) == 0x0001CC, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_int_Variable_6' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, K2Node_Event_player) == 0x0001D0, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::K2Node_Event_player' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, K2Node_Event_hit) == 0x0001D8, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::K2Node_Event_hit' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, K2Node_Event_action) == 0x000260, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::K2Node_Event_action' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, Temp_int_Variable_7) == 0x000264, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::Temp_int_Variable_7' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_LessEqual_IntInt_ReturnValue_5) == 0x000268, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_LessEqual_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Add_IntInt_ReturnValue_5) == 0x00026C, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, K2Node_SwitchEnum_CmpSuccess) == 0x000270, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000274, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_GetActorScale3D_ReturnValue) == 0x000280, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_GetActorScale3D_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Add_VectorVector_ReturnValue) == 0x00028C, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_BreakVector_X) == 0x000298, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_BreakVector_Y) == 0x00029C, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_BreakVector_Z) == 0x0002A0, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_MakeTransform_ReturnValue) == 0x0002B0, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_MultiplyMultiply_FloatFloat_ReturnValue) == 0x0002E0, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_MultiplyMultiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x0002E8, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x0002F0, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_FinishSpawningActor_ReturnValue) == 0x0002F8, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Round_ReturnValue) == 0x000300, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Round_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, K2Node_DynamicCast_AsInt_Player) == 0x000308, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::K2Node_DynamicCast_AsInt_Player' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, K2Node_DynamicCast_bSuccess) == 0x000318, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Subtract_IntInt_ReturnValue) == 0x00031C, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_asProp_return) == 0x000320, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_asProp_return' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_LessEqual_IntInt_ReturnValue_6) == 0x000328, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_LessEqual_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Conv_NameToString_ReturnValue) == 0x000330, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000340, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1) == 0x000348, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000350, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_MultiplyMultiply_FloatFloat_ReturnValue_1) == 0x000354, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_MultiplyMultiply_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_FinishSpawningActor_ReturnValue_1) == 0x000358, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_FinishSpawningActor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Conv_FloatToVector_ReturnValue) == 0x000360, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Conv_FloatToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2) == 0x000370, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_FinishSpawningActor_ReturnValue_2) == 0x000378, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_FinishSpawningActor_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000380, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_MakeTransform_ReturnValue_1) == 0x000390, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_MakeTransform_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_3) == 0x0003C0, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_4) == 0x0003C8, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_FinishSpawningActor_ReturnValue_3) == 0x0003D0, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_FinishSpawningActor_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, K2Node_DynamicCast_AsInt_Player_1) == 0x0003D8, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::K2Node_DynamicCast_AsInt_Player_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, K2Node_DynamicCast_bSuccess_1) == 0x0003E8, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_FinishSpawningActor_ReturnValue_4) == 0x0003F0, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_FinishSpawningActor_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_asProp_return_1) == 0x0003F8, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_asProp_return_1' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_5) == 0x000400, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_FinishSpawningActor_ReturnValue_5) == 0x000408, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_FinishSpawningActor_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ExecuteUbergraph_prop_doughball, CallFunc_Conv_NameToString_ReturnValue_1) == 0x000410, "Member 'Prop_doughball_C_ExecuteUbergraph_prop_doughball::CallFunc_Conv_NameToString_ReturnValue_1' has a wrong offset!");

// Function prop_doughball.prop_doughball_C.actionOptionIndex
// 0x0098 (0x0098 - 0x0000)
struct Prop_doughball_C_ActionOptionIndex final
{
public:
	class AMainPlayer_C*                          Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit_0;                                             // 0x0008(0x0088)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	Enum_interactionActions                       Action;                                            // 0x0090(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_doughball_C_ActionOptionIndex) == 0x000008, "Wrong alignment on Prop_doughball_C_ActionOptionIndex");
static_assert(sizeof(Prop_doughball_C_ActionOptionIndex) == 0x000098, "Wrong size on Prop_doughball_C_ActionOptionIndex");
static_assert(offsetof(Prop_doughball_C_ActionOptionIndex, Player) == 0x000000, "Member 'Prop_doughball_C_ActionOptionIndex::Player' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ActionOptionIndex, Hit_0) == 0x000008, "Member 'Prop_doughball_C_ActionOptionIndex::Hit_0' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_ActionOptionIndex, Action) == 0x000090, "Member 'Prop_doughball_C_ActionOptionIndex::Action' has a wrong offset!");

// Function prop_doughball.prop_doughball_C.getActionOptions
// 0x0060 (0x0060 - 0x0000)
struct Prop_doughball_C_GetActionOptions final
{
public:
	class AMainPlayer_C*                          Player;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    Component;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Actor;                                             // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         Options;                                           // 0x0018(0x0010)(Parm, OutParm)
	TArray<Enum_interactionActions>               Options_enum;                                      // 0x0028(0x0010)(Parm, OutParm)
	TArray<class FText>                           OptionsNamesOverlay;                               // 0x0038(0x0010)(Parm, OutParm)
	uint8                                         Number;                                            // 0x0048(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<Enum_interactionActions>               K2Node_MakeArray_Array;                            // 0x0050(0x0010)(ReferenceParm)
};
static_assert(alignof(Prop_doughball_C_GetActionOptions) == 0x000008, "Wrong alignment on Prop_doughball_C_GetActionOptions");
static_assert(sizeof(Prop_doughball_C_GetActionOptions) == 0x000060, "Wrong size on Prop_doughball_C_GetActionOptions");
static_assert(offsetof(Prop_doughball_C_GetActionOptions, Player) == 0x000000, "Member 'Prop_doughball_C_GetActionOptions::Player' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_GetActionOptions, Component) == 0x000008, "Member 'Prop_doughball_C_GetActionOptions::Component' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_GetActionOptions, Actor) == 0x000010, "Member 'Prop_doughball_C_GetActionOptions::Actor' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_GetActionOptions, Options) == 0x000018, "Member 'Prop_doughball_C_GetActionOptions::Options' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_GetActionOptions, Options_enum) == 0x000028, "Member 'Prop_doughball_C_GetActionOptions::Options_enum' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_GetActionOptions, OptionsNamesOverlay) == 0x000038, "Member 'Prop_doughball_C_GetActionOptions::OptionsNamesOverlay' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_GetActionOptions, Number) == 0x000048, "Member 'Prop_doughball_C_GetActionOptions::Number' has a wrong offset!");
static_assert(offsetof(Prop_doughball_C_GetActionOptions, K2Node_MakeArray_Array) == 0x000050, "Member 'Prop_doughball_C_GetActionOptions::K2Node_MakeArray_Array' has a wrong offset!");

}

