#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_toolbox

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Prop_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass prop_toolbox.prop_toolbox_C
// 0x0010 (0x0368 - 0x0358)
class AProp_toolbox_C final : public AProp_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Prop_toolbox_C;                     // 0x0358(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         Fixes;                                             // 0x0360(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_prop_toolbox(int32 EntryPoint);
	void BndEvt__StaticMesh_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit_0);
	void PlayerHandUse_LMB(class AMainPlayer_C* Player);
	void LoadData(const struct FStruct_save& Data, bool* Return);
	void GetData(struct FStruct_save* Data);
	void LookAt(class AMainPlayer_C* Player, const struct FHitResult& Hit_0, bool* Return, class FString* Text, class UPrimitiveComponent** boundObjectReplace, uint8* Number);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"prop_toolbox_C">();
	}
	static class AProp_toolbox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_toolbox_C>();
	}
};
static_assert(alignof(AProp_toolbox_C) == 0x000008, "Wrong alignment on AProp_toolbox_C");
static_assert(sizeof(AProp_toolbox_C) == 0x000368, "Wrong size on AProp_toolbox_C");
static_assert(offsetof(AProp_toolbox_C, UberGraphFrame_Prop_toolbox_C) == 0x000358, "Member 'AProp_toolbox_C::UberGraphFrame_Prop_toolbox_C' has a wrong offset!");
static_assert(offsetof(AProp_toolbox_C, Fixes) == 0x000360, "Member 'AProp_toolbox_C::Fixes' has a wrong offset!");

}

