#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_safe

#include "Basic.hpp"

#include "Struct_save_structs.hpp"
#include "Struct_mString_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Struct_mBool_structs.hpp"
#include "Struct_food_structs.hpp"
#include "Struct_prop3_structs.hpp"
#include "PhysicsCore_structs.hpp"


namespace SDK::Params
{

// Function prop_safe.prop_safe_C.getData
// 0x02E0 (0x02E0 - 0x0000)
struct Prop_safe_C_GetData final
{
public:
	struct FStruct_save                           Data;                                              // 0x0000(0x00C0)(Parm, OutParm, HasGetValueTypeHash)
	TArray<class FString>                         K2Node_MakeArray_Array;                            // 0x00C0(0x0010)(ReferenceParm)
	struct FStruct_mString                        K2Node_MakeStruct_struct_mString;                  // 0x00D0(0x0010)(HasGetValueTypeHash)
	struct FStruct_mString                        K2Node_MakeStruct_struct_mString_1;                // 0x00E0(0x0010)(HasGetValueTypeHash)
	struct FStruct_save                           CallFunc_getData_data;                             // 0x00F0(0x00C0)(HasGetValueTypeHash)
	TArray<bool>                                  K2Node_MakeArray_Array_1;                          // 0x01B0(0x0010)(ReferenceParm)
	struct FStruct_mBool                          K2Node_MakeStruct_struct_mBool;                    // 0x01C0(0x0010)(HasGetValueTypeHash)
	struct FStruct_mString                        CallFunc_Array_Get_Item;                           // 0x01D0(0x0010)(HasGetValueTypeHash)
	struct FStruct_mString                        CallFunc_Array_Get_Item_1;                         // 0x01E0(0x0010)(HasGetValueTypeHash)
	struct FStruct_mBool                          CallFunc_Array_Get_Item_2;                         // 0x01F0(0x0010)(HasGetValueTypeHash)
	TArray<struct FStruct_mString>                K2Node_MakeArray_Array_2;                          // 0x0200(0x0010)(ReferenceParm)
	TArray<struct FStruct_mBool>                  K2Node_MakeArray_Array_3;                          // 0x0210(0x0010)(ReferenceParm)
	struct FStruct_save                           K2Node_SetFieldsInStruct_StructOut;                // 0x0220(0x00C0)(HasGetValueTypeHash)
};
static_assert(alignof(Prop_safe_C_GetData) == 0x000010, "Wrong alignment on Prop_safe_C_GetData");
static_assert(sizeof(Prop_safe_C_GetData) == 0x0002E0, "Wrong size on Prop_safe_C_GetData");
static_assert(offsetof(Prop_safe_C_GetData, Data) == 0x000000, "Member 'Prop_safe_C_GetData::Data' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, K2Node_MakeArray_Array) == 0x0000C0, "Member 'Prop_safe_C_GetData::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, K2Node_MakeStruct_struct_mString) == 0x0000D0, "Member 'Prop_safe_C_GetData::K2Node_MakeStruct_struct_mString' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, K2Node_MakeStruct_struct_mString_1) == 0x0000E0, "Member 'Prop_safe_C_GetData::K2Node_MakeStruct_struct_mString_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, CallFunc_getData_data) == 0x0000F0, "Member 'Prop_safe_C_GetData::CallFunc_getData_data' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, K2Node_MakeArray_Array_1) == 0x0001B0, "Member 'Prop_safe_C_GetData::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, K2Node_MakeStruct_struct_mBool) == 0x0001C0, "Member 'Prop_safe_C_GetData::K2Node_MakeStruct_struct_mBool' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, CallFunc_Array_Get_Item) == 0x0001D0, "Member 'Prop_safe_C_GetData::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, CallFunc_Array_Get_Item_1) == 0x0001E0, "Member 'Prop_safe_C_GetData::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, CallFunc_Array_Get_Item_2) == 0x0001F0, "Member 'Prop_safe_C_GetData::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, K2Node_MakeArray_Array_2) == 0x000200, "Member 'Prop_safe_C_GetData::K2Node_MakeArray_Array_2' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, K2Node_MakeArray_Array_3) == 0x000210, "Member 'Prop_safe_C_GetData::K2Node_MakeArray_Array_3' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_GetData, K2Node_SetFieldsInStruct_StructOut) == 0x000220, "Member 'Prop_safe_C_GetData::K2Node_SetFieldsInStruct_StructOut' has a wrong offset!");

// Function prop_safe.prop_safe_C.loadData
// 0x0110 (0x0110 - 0x0000)
struct Prop_safe_C_LoadData final
{
public:
	struct FStruct_save                           Data;                                              // 0x0000(0x00C0)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
	bool                                          Return;                                            // 0x00C0(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_loadData_return;                          // 0x00C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C2[0x6];                                       // 0x00C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_mString                        CallFunc_Array_Get_Item;                           // 0x00C8(0x0010)(HasGetValueTypeHash)
	struct FStruct_mString                        CallFunc_Array_Get_Item_1;                         // 0x00D8(0x0010)(HasGetValueTypeHash)
	class FString                                 CallFunc_Array_Get_Item_2;                         // 0x00E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FStruct_mBool                          CallFunc_Array_Get_Item_3;                         // 0x00F8(0x0010)(HasGetValueTypeHash)
	bool                                          CallFunc_Array_Get_Item_4;                         // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Prop_safe_C_LoadData) == 0x000010, "Wrong alignment on Prop_safe_C_LoadData");
static_assert(sizeof(Prop_safe_C_LoadData) == 0x000110, "Wrong size on Prop_safe_C_LoadData");
static_assert(offsetof(Prop_safe_C_LoadData, Data) == 0x000000, "Member 'Prop_safe_C_LoadData::Data' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_LoadData, Return) == 0x0000C0, "Member 'Prop_safe_C_LoadData::Return' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_LoadData, CallFunc_loadData_return) == 0x0000C1, "Member 'Prop_safe_C_LoadData::CallFunc_loadData_return' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_LoadData, CallFunc_Array_Get_Item) == 0x0000C8, "Member 'Prop_safe_C_LoadData::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_LoadData, CallFunc_Array_Get_Item_1) == 0x0000D8, "Member 'Prop_safe_C_LoadData::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_LoadData, CallFunc_Array_Get_Item_2) == 0x0000E8, "Member 'Prop_safe_C_LoadData::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_LoadData, CallFunc_Array_Get_Item_3) == 0x0000F8, "Member 'Prop_safe_C_LoadData::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_LoadData, CallFunc_Array_Get_Item_4) == 0x000108, "Member 'Prop_safe_C_LoadData::CallFunc_Array_Get_Item_4' has a wrong offset!");

// Function prop_safe.prop_safe_C.opened
// 0x0210 (0x0210 - 0x0000)
struct Prop_safe_C_Opened final
{
public:
	int32                                         Temp_int_Variable;                                 // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_2;                               // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_1;           // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_RandomPointInBoundingBox_ReturnValue;     // 0x0028(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0xC];                                       // 0x0034(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0040(0x0030)(ConstParm, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x0070(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_TransformLocation_ReturnValue;            // 0x007C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0090(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1; // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AProp_C*                                CallFunc_FinishSpawningActor_ReturnValue;          // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AProp_food_C*                           CallFunc_FinishSpawningActor_ReturnValue_1;        // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue_2;           // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x3];                                       // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EC[0x4];                                       // 0x00EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Array_Get_Item;                           // 0x00F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x3];                                      // 0x0101(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x0104(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_propToObject_ReturnValue;                 // 0x010C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_10D[0x3];                                      // 0x010D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_food                           CallFunc_propToObject_foodData;                    // 0x0110(0x001C)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12C[0x4];                                      // 0x012C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 CallFunc_propToObject_object;                      // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_propToObject_isFood;                      // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_139[0x7];                                      // 0x0139(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStruct_prop3                          CallFunc_propToObject_fuckYouRetard;               // 0x0140(0x0080)(HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2; // 0x01C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValidClass_ReturnValue;                 // 0x01C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C9[0x7];                                      // 0x01C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_FinishSpawningActor_ReturnValue_2;        // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IInt_player_C>         K2Node_DynamicCast_AsInt_Player;                   // 0x01D8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AProp_C*                                CallFunc_asProp_return;                            // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_NameToString_ReturnValue;            // 0x01F8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_safe_C_Opened) == 0x000010, "Wrong alignment on Prop_safe_C_Opened");
static_assert(sizeof(Prop_safe_C_Opened) == 0x000210, "Wrong size on Prop_safe_C_Opened");
static_assert(offsetof(Prop_safe_C_Opened, Temp_int_Variable) == 0x000000, "Member 'Prop_safe_C_Opened::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000004, "Member 'Prop_safe_C_Opened::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'Prop_safe_C_Opened::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, Temp_int_Variable_1) == 0x00000C, "Member 'Prop_safe_C_Opened::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, Temp_int_Variable_2) == 0x000010, "Member 'Prop_safe_C_Opened::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_LessEqual_IntInt_ReturnValue_1) == 0x000014, "Member 'Prop_safe_C_Opened::CallFunc_LessEqual_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_Add_IntInt_ReturnValue_1) == 0x000018, "Member 'Prop_safe_C_Opened::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, Temp_int_Loop_Counter_Variable) == 0x00001C, "Member 'Prop_safe_C_Opened::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_Add_IntInt_ReturnValue_2) == 0x000020, "Member 'Prop_safe_C_Opened::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, Temp_int_Array_Index_Variable) == 0x000024, "Member 'Prop_safe_C_Opened::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_RandomPointInBoundingBox_ReturnValue) == 0x000028, "Member 'Prop_safe_C_Opened::CallFunc_RandomPointInBoundingBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_GetTransform_ReturnValue) == 0x000040, "Member 'Prop_safe_C_Opened::CallFunc_GetTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_K2_GetActorRotation_ReturnValue) == 0x000070, "Member 'Prop_safe_C_Opened::CallFunc_K2_GetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_TransformLocation_ReturnValue) == 0x00007C, "Member 'Prop_safe_C_Opened::CallFunc_TransformLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, Temp_int_Variable_3) == 0x000088, "Member 'Prop_safe_C_Opened::Temp_int_Variable_3' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_MakeTransform_ReturnValue) == 0x000090, "Member 'Prop_safe_C_Opened::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x0000C0, "Member 'Prop_safe_C_Opened::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1) == 0x0000C8, "Member 'Prop_safe_C_Opened::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_FinishSpawningActor_ReturnValue) == 0x0000D0, "Member 'Prop_safe_C_Opened::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_FinishSpawningActor_ReturnValue_1) == 0x0000D8, "Member 'Prop_safe_C_Opened::CallFunc_FinishSpawningActor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_LessEqual_IntInt_ReturnValue_2) == 0x0000E0, "Member 'Prop_safe_C_Opened::CallFunc_LessEqual_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_Add_IntInt_ReturnValue_3) == 0x0000E4, "Member 'Prop_safe_C_Opened::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_Array_Length_ReturnValue) == 0x0000E8, "Member 'Prop_safe_C_Opened::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_Array_Get_Item) == 0x0000F0, "Member 'Prop_safe_C_Opened::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_Less_IntInt_ReturnValue) == 0x000100, "Member 'Prop_safe_C_Opened::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_Conv_StringToName_ReturnValue) == 0x000104, "Member 'Prop_safe_C_Opened::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_propToObject_ReturnValue) == 0x00010C, "Member 'Prop_safe_C_Opened::CallFunc_propToObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_propToObject_foodData) == 0x000110, "Member 'Prop_safe_C_Opened::CallFunc_propToObject_foodData' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_propToObject_object) == 0x000130, "Member 'Prop_safe_C_Opened::CallFunc_propToObject_object' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_propToObject_isFood) == 0x000138, "Member 'Prop_safe_C_Opened::CallFunc_propToObject_isFood' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_propToObject_fuckYouRetard) == 0x000140, "Member 'Prop_safe_C_Opened::CallFunc_propToObject_fuckYouRetard' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2) == 0x0001C0, "Member 'Prop_safe_C_Opened::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_IsValidClass_ReturnValue) == 0x0001C8, "Member 'Prop_safe_C_Opened::CallFunc_IsValidClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_FinishSpawningActor_ReturnValue_2) == 0x0001D0, "Member 'Prop_safe_C_Opened::CallFunc_FinishSpawningActor_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, K2Node_DynamicCast_AsInt_Player) == 0x0001D8, "Member 'Prop_safe_C_Opened::K2Node_DynamicCast_AsInt_Player' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, K2Node_DynamicCast_bSuccess) == 0x0001E8, "Member 'Prop_safe_C_Opened::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_asProp_return) == 0x0001F0, "Member 'Prop_safe_C_Opened::CallFunc_asProp_return' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_Opened, CallFunc_Conv_NameToString_ReturnValue) == 0x0001F8, "Member 'Prop_safe_C_Opened::CallFunc_Conv_NameToString_ReturnValue' has a wrong offset!");

// Function prop_safe.prop_safe_C.updLock
// 0x0050 (0x0050 - 0x0000)
struct Prop_safe_C_UpdLock final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EAngularConstraintMotion                      Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAngularConstraintMotion                      Temp_byte_Variable_1;                              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3[0x1];                                        // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_SelectRotator_ReturnValue;                // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0010(0x0030)(IsPlainOldData, NoDestructor)
	EAngularConstraintMotion                      K2Node_Select_Default;                             // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_safe_C_UpdLock) == 0x000010, "Wrong alignment on Prop_safe_C_UpdLock");
static_assert(sizeof(Prop_safe_C_UpdLock) == 0x000050, "Wrong size on Prop_safe_C_UpdLock");
static_assert(offsetof(Prop_safe_C_UpdLock, Temp_bool_Variable) == 0x000000, "Member 'Prop_safe_C_UpdLock::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_UpdLock, Temp_byte_Variable) == 0x000001, "Member 'Prop_safe_C_UpdLock::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_UpdLock, Temp_byte_Variable_1) == 0x000002, "Member 'Prop_safe_C_UpdLock::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_UpdLock, CallFunc_SelectRotator_ReturnValue) == 0x000004, "Member 'Prop_safe_C_UpdLock::CallFunc_SelectRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_UpdLock, CallFunc_MakeTransform_ReturnValue) == 0x000010, "Member 'Prop_safe_C_UpdLock::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_UpdLock, K2Node_Select_Default) == 0x000040, "Member 'Prop_safe_C_UpdLock::K2Node_Select_Default' has a wrong offset!");

// Function prop_safe.prop_safe_C.ExecuteUbergraph_prop_safe
// 0x0130 (0x0130 - 0x0000)
struct Prop_safe_C_ExecuteUbergraph_prop_safe final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue;         // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue_1;       // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_1;           // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue_2;       // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_2;           // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue_3;       // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_3;           // 0x0070(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue_4;       // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_2;              // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_4;           // 0x0098(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue_5;       // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_3;              // 0x00B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_5;           // 0x00C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue_6;       // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D4[0x4];                                       // 0x00D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_4;              // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_6;           // 0x00E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue_7;       // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FC[0x4];                                       // 0x00FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_5;              // 0x0100(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue_7;           // 0x0110(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_6;              // 0x0120(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_safe_C_ExecuteUbergraph_prop_safe) == 0x000008, "Wrong alignment on Prop_safe_C_ExecuteUbergraph_prop_safe");
static_assert(sizeof(Prop_safe_C_ExecuteUbergraph_prop_safe) == 0x000130, "Wrong size on Prop_safe_C_ExecuteUbergraph_prop_safe");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, EntryPoint) == 0x000000, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::EntryPoint' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_IsEmpty_ReturnValue) == 0x000004, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_IsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_RandomIntegerInRange_ReturnValue) == 0x000008, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_RandomIntegerInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_RandomIntegerInRange_ReturnValue_1) == 0x00000C, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_RandomIntegerInRange_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Conv_IntToString_ReturnValue) == 0x000010, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Conv_IntToString_ReturnValue_1) == 0x000020, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Conv_IntToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_RandomIntegerInRange_ReturnValue_2) == 0x000030, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_RandomIntegerInRange_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Concat_StrStr_ReturnValue) == 0x000038, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Conv_IntToString_ReturnValue_2) == 0x000048, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Conv_IntToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_RandomIntegerInRange_ReturnValue_3) == 0x000058, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_RandomIntegerInRange_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Concat_StrStr_ReturnValue_1) == 0x000060, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Conv_IntToString_ReturnValue_3) == 0x000070, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Conv_IntToString_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_RandomIntegerInRange_ReturnValue_4) == 0x000080, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_RandomIntegerInRange_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Concat_StrStr_ReturnValue_2) == 0x000088, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Concat_StrStr_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Conv_IntToString_ReturnValue_4) == 0x000098, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Conv_IntToString_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_RandomIntegerInRange_ReturnValue_5) == 0x0000A8, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_RandomIntegerInRange_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Concat_StrStr_ReturnValue_3) == 0x0000B0, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Concat_StrStr_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Conv_IntToString_ReturnValue_5) == 0x0000C0, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Conv_IntToString_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_RandomIntegerInRange_ReturnValue_6) == 0x0000D0, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_RandomIntegerInRange_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Concat_StrStr_ReturnValue_4) == 0x0000D8, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Concat_StrStr_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Conv_IntToString_ReturnValue_6) == 0x0000E8, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Conv_IntToString_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_RandomIntegerInRange_ReturnValue_7) == 0x0000F8, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_RandomIntegerInRange_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Concat_StrStr_ReturnValue_5) == 0x000100, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Concat_StrStr_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Conv_IntToString_ReturnValue_7) == 0x000110, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Conv_IntToString_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(Prop_safe_C_ExecuteUbergraph_prop_safe, CallFunc_Concat_StrStr_ReturnValue_6) == 0x000120, "Member 'Prop_safe_C_ExecuteUbergraph_prop_safe::CallFunc_Concat_StrStr_ReturnValue_6' has a wrong offset!");

}

