#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_mannequin

#include "Basic.hpp"


namespace SDK::Params
{

// Function prop_mannequin.prop_mannequin_C.ExecuteUbergraph_prop_mannequin
// 0x0008 (0x0008 - 0x0000)
struct Prop_mannequin_C_ExecuteUbergraph_prop_mannequin final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VictoryFloatPlusEquals_FloatOut;          // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prop_mannequin_C_ExecuteUbergraph_prop_mannequin) == 0x000004, "Wrong alignment on Prop_mannequin_C_ExecuteUbergraph_prop_mannequin");
static_assert(sizeof(Prop_mannequin_C_ExecuteUbergraph_prop_mannequin) == 0x000008, "Wrong size on Prop_mannequin_C_ExecuteUbergraph_prop_mannequin");
static_assert(offsetof(Prop_mannequin_C_ExecuteUbergraph_prop_mannequin, EntryPoint) == 0x000000, "Member 'Prop_mannequin_C_ExecuteUbergraph_prop_mannequin::EntryPoint' has a wrong offset!");
static_assert(offsetof(Prop_mannequin_C_ExecuteUbergraph_prop_mannequin, CallFunc_VictoryFloatPlusEquals_FloatOut) == 0x000004, "Member 'Prop_mannequin_C_ExecuteUbergraph_prop_mannequin::CallFunc_VictoryFloatPlusEquals_FloatOut' has a wrong offset!");

}

