#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_food_showberry

#include "Basic.hpp"

#include "Prop_food_showberry_classes.hpp"
#include "Prop_food_showberry_parameters.hpp"


namespace SDK
{

// Function prop_food_showberry.prop_food_showberry_C.ExecuteUbergraph_prop_food_showberry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AProp_food_showberry_C::ExecuteUbergraph_prop_food_showberry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("prop_food_showberry_C", "ExecuteUbergraph_prop_food_showberry");

	Params::Prop_food_showberry_C_ExecuteUbergraph_prop_food_showberry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function prop_food_showberry.prop_food_showberry_C.eaten
// (Public, BlueprintCallable, BlueprintEvent)

void AProp_food_showberry_C::Eaten()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("prop_food_showberry_C", "eaten");

	UObject::ProcessEvent(Func, nullptr);
}

}

