#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Rockcandle

#include "Basic.hpp"


namespace SDK::Params
{

// Function rockcandle.rockcandle_C.ExecuteUbergraph_rockcandle
// 0x0004 (0x0004 - 0x0000)
struct Rockcandle_C_ExecuteUbergraph_rockcandle final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Rockcandle_C_ExecuteUbergraph_rockcandle) == 0x000004, "Wrong alignment on Rockcandle_C_ExecuteUbergraph_rockcandle");
static_assert(sizeof(Rockcandle_C_ExecuteUbergraph_rockcandle) == 0x000004, "Wrong size on Rockcandle_C_ExecuteUbergraph_rockcandle");
static_assert(offsetof(Rockcandle_C_ExecuteUbergraph_rockcandle, EntryPoint) == 0x000000, "Member 'Rockcandle_C_ExecuteUbergraph_rockcandle::EntryPoint' has a wrong offset!");

}

