#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Trigger_bloodSkeleton

#include "Basic.hpp"

#include "Trigger_bloodSkeleton_classes.hpp"
#include "Trigger_bloodSkeleton_parameters.hpp"


namespace SDK
{

// Function trigger_bloodSkeleton.trigger_bloodSkeleton_C.runTrigger
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Owner_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATrigger_bloodSkeleton_C::RunTrigger(class AActor* Owner_0, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("trigger_bloodSkeleton_C", "runTrigger");

	Params::Trigger_bloodSkeleton_C_RunTrigger Parms{};

	Parms.Owner_0 = Owner_0;
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function trigger_bloodSkeleton.trigger_bloodSkeleton_C.ExecuteUbergraph_trigger_bloodSkeleton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATrigger_bloodSkeleton_C::ExecuteUbergraph_trigger_bloodSkeleton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("trigger_bloodSkeleton_C", "ExecuteUbergraph_trigger_bloodSkeleton");

	Params::Trigger_bloodSkeleton_C_ExecuteUbergraph_trigger_bloodSkeleton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

