#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UfoDropper_pig

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UfoDropper_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ufoDropper_pig.ufoDropper_pig_C
// 0x0008 (0x02C8 - 0x02C0)
class AUfoDropper_pig_C final : public AUfoDropper_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_UfoDropper_pig_C;                   // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_ufoDropper_pig(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ufoDropper_pig_C">();
	}
	static class AUfoDropper_pig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AUfoDropper_pig_C>();
	}
};
static_assert(alignof(AUfoDropper_pig_C) == 0x000008, "Wrong alignment on AUfoDropper_pig_C");
static_assert(sizeof(AUfoDropper_pig_C) == 0x0002C8, "Wrong size on AUfoDropper_pig_C");
static_assert(offsetof(AUfoDropper_pig_C, UberGraphFrame_UfoDropper_pig_C) == 0x0002C0, "Member 'AUfoDropper_pig_C::UberGraphFrame_UfoDropper_pig_C' has a wrong offset!");

}

