#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VoidModActor

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VoidModActor.VoidModActor_C
// 0x0008 (0x0228 - 0x0220)
class AVoidModActor_C : public AActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void InitializeSave();
	void InitializeMod();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VoidModActor_C">();
	}
	static class AVoidModActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVoidModActor_C>();
	}
};
static_assert(alignof(AVoidModActor_C) == 0x000008, "Wrong alignment on AVoidModActor_C");
static_assert(sizeof(AVoidModActor_C) == 0x000228, "Wrong size on AVoidModActor_C");
static_assert(offsetof(AVoidModActor_C, DefaultSceneRoot) == 0x000220, "Member 'AVoidModActor_C::DefaultSceneRoot' has a wrong offset!");

}

